logFilters:
  - code: YN0013
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

npmAuthToken: "${NODE_AUTH_TOKEN:-fallback}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
